In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

To get equaly ranged elements between start and end

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

To get the random numbers

In [14]:
np.random.rand(3,5)

array([[0.09848451, 0.17863873, 0.25449733, 0.08713935, 0.83635118],
       [0.11027293, 0.99245671, 0.58934573, 0.69028247, 0.19208743],
       [0.79455368, 0.83522012, 0.36534108, 0.84909812, 0.96397239]])

In [15]:
np.random.randn(3,5)

array([[ 1.15473427,  1.55024189, -0.16107216,  1.03366683,  1.18297337],
       [-0.61238518,  0.5192535 ,  1.21242471,  0.25282722,  1.7030981 ],
       [ 2.00047766, -0.39485827, -0.62232211, -0.50863707,  2.36818098]])

Reshaping single array to matrix


In [25]:
arr=np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr=np.arange(10)

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Broadcasting

In [44]:
arr=np.arange(11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5]=100

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Marix Broadcasting

In [52]:
matr=np.arange(25).reshape(5,5)
matr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
matr[2:,2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [55]:
# COonditional Selection

In [57]:

arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [61]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [60]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [63]:

# Numpy way to do this

arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
np.arange(100).reshape(10,10)/100

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [95]:
# Seed in random numbers
np.random.seed(3)

np.random.rand(1)

array([0.5507979])

In [114]:
np.random.rand(1)

array([0.4151012])